DATA:
  IMG_SIZE: 384
  ADD_META: True
TRAIN:
  USE_ARCFACE: True
MODEL:
  TYPE: MetaFG
  NAME: MetaFG_meta_0
  EXTRA_TOKEN_NUM: 5
  META_DIMS: [4, 34, 32, 31]
#   META_DIMS: [4, 97]
AUG:
  MIXUP: 0.
  CUTMIX: 0.
# TRAIN:
#   NEVER_MASK: True